### ISSUE TITLE
求助，未查询到域控

### ISSUE THREAD

**Issue by rvnox** [Qihoo360/WatchAD2.0#15]
域控为windows server2022，搭建好后，web页面登陆数据库中没有用户，进入docker容器后重新初始化，显示无法查询到域控，具体如下：
![image](https://github.com/Qihoo360/WatchAD2.0/assets/67718036/ef25c96c-5d89-49b2-82fe-9cf1431396aa)

是因为linux没有加入到域的原因吗 ？？？还是和windows server2022有关呀

具体.env如下：
#KAFKA配置，需修改为当前服务器的IP
KAFKAHOST=192.168.131.128
KAFKAADV=PLAINTEXT://192.168.131.128:9092
BROKER=192.168.131.128:9092

#Mongo配置，默认账号密码
MONGOUSER=IATP
MONGOPWD=IATP-by-360
  
#域控配置，其中DCUSER为域内用户的DN
DCNAME="zgtest.local"
DCSERVER=192.168.131.131
DCUSER="CN=Administrator,CN=Users,DC=zgtest,DC=local"
DCPWD="Admin123"

#WEB配置，可配置为域内任意用户，或DCUSER的CN
WEBUSER="Administrator"

**Comment by u-raison** [comment]
好家伙，我的也是，而且我的压根就没有80端口被启用的，无法进入web页面

**Comment by Sculptor-liu** [comment]
请问解决了嘛

**Comment by Cgaii** [comment]
> 域控为windows server2022，搭建好后，web页面登陆数据库中没有用户，进入docker容器后重新初始化，显示无法查询到域控，具体如下： ![image](https://private-user-images.githubusercontent.com/67718036/305646904-ef25c96c-5d89-49b2-82fe-9cf1431396aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0OTc3NDAsIm5iZiI6MTcwODQ5NzQ0MCwicGF0aCI6Ii82NzcxODAzNi8zMDU2NDY5MDQtZWYyNWM5NmMtNWQ4OS00OWIyLTgyZmUtOWNmMTQzMTM5NmFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDA2MzcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiNTA2MjUyOGUzNzE4YjFkYzY2YmM4YmM4OTFkODIxZWJkNDY3NmQ3NGU2NGRjMTFjZmU0MTVjYmIyY2Y4MWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YFcD114ZAASNcQB-PndqXVlOmrK2sOtc3dsMl8CVoG8)
> 
> 是因为linux没有加入到域的原因吗 ？？？还是和windows server2022有关呀
> 
> 具体.env如下： #KAFKA配置，需修改为当前服务器的IP KAFKAHOST=192.168.131.128 KAFKAADV=PLAINTEXT://192.168.131.128:9092 BROKER=192.168.131.128:9092
> 
> #Mongo配置，默认账号密码 MONGOUSER=IATP MONGOPWD=IATP-by-360
> 
> #域控配置，其中DCUSER为域内用户的DN DCNAME="zgtest.local" DCSERVER=192.168.131.131 DCUSER="CN=Administrator,CN=Users,DC=zgtest,DC=local" DCPWD="Admin123"
> 
> #WEB配置，可配置为域内任意用户，或DCUSER的CN WEBUSER="Administrator"

@ayuxy 
你的截图中使用的--username是Administrator，需要替换成DN：--username "CN=Administrator,CN=Users,DC=zgtest,DC=local"，再尝试下能否连上。

**Comment by Sculptor-liu** [comment]
[root@sculptor-virtual-machine home]# ls
engine.log  entrypoint.sh  iatp  iatp_wbm  web.log
[root@sculptor-virtual-machine home]# ./iatp init --mongourl mongodb://mongo: password@127.0.0.1:27017 --domainname dzzjy.com --domainserver 192.168.1.100 --username "CN=Administrator,CN=Users,DC=dzzjy,DC=com" --password "@admin123"
[+] DZZJY 域注册成功.
[+] 数据编号: 65d59fdf097c3f7259f2539d.
{"DomainName":"dzzjy.com","DomainServer":"192.168.1.100","KDCServerName":"WIN-M3D5HBADTCH.DZZJY.COM","UserName":"CN=Administrator,CN=Users,DC=dzzjy,DC=com","PassWord":"admin","DomainControls":["WIN-M3D5HBADTCH"],"NetbiosDomain":"DZZJY","SSL":false}
[root@sculptor-virtual-machine home]# ./iatp init --mongourl mongodb://mongo: password@127.0.0.1:27017 --index
创建日志缓存....
[root@sculptor-virtual-machine home]# ./iatp web --init --authdomain dzzjy.com --user Administrator
[-]认证域配置失败:数据库中未注册该域信息, server selection error: server selection timeout, current topology: { Type: Unknown, Servers: [{ Addr: mongo:, Type: Unknown, Last error: connection() error occured during connection handshake: dial tcp: lookup mongo: no such host }, ] }
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe25a43]

goroutine 1 [running]:
iatp/cmd.glob..func4(0x1a7f740, {0x1039ae7, 0x5, 0x5})
	/go/src/iatp_opensource/cmd/web.go:55 +0x1a3
github.com/spf13/cobra.(*Command).execute(0x1a7f740, {0xc00011a910, 0x5, 0x5})
	/go/src/iatp_opensource/vendor/github.com/spf13/cobra/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0x1a7efc0)
	/go/src/iatp_opensource/vendor/github.com/spf13/cobra/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/iatp_opensource/vendor/github.com/spf13/cobra/command.go:902
iatp/cmd.Execute()
	/go/src/iatp_opensource/cmd/root.go:47 +0x25
main.main()
	/go/src/iatp_opensource/main.go:21 +0x17
[root@sculptor-virtual-machine home]#

**Comment by Sculptor-liu** [comment]
[root@sculptor-virtual-machine home]# ls
engine.log  entrypoint.sh  iatp  iatp_wbm  web.log
[root@sculptor-virtual-machine home]# ./iatp init --mongourl mongodb://mongo: password@127.0.0.1:27017 --domainname dzzjy.com --domainserver 192.168.1.100 --username "CN=Administrator,CN=Users,DC=dzzjy,DC=com" --password "admin"
[+] DZZJY 域注册成功.
[+] 数据编号: 65d59fdf097c3f7259f2539d.
{"DomainName":"dzzjy.com","DomainServer":"192.168.1.100","KDCServerName":"WIN-M3D5HBADTCH.DZZJY.COM","UserName":"CN=Administrator,CN=Users,DC=dzzjy,DC=com","PassWord":"admin","DomainControls":["WIN-M3D5HBADTCH"],"NetbiosDomain":"DZZJY","SSL":false}
[root@sculptor-virtual-machine home]# ./iatp init --mongourl mongodb://mongo: password@127.0.0.1:27017 --index
创建日志缓存....
[root@sculptor-virtual-machine home]# ./iatp web --init --authdomain dzzjy.com --user Administrator
[-]认证域配置失败:数据库中未注册该域信息, server selection error: server selection timeout, current topology: { Type: Unknown, Servers: [{ Addr: mongo:, Type: Unknown, Last error: connection() error occured during connection handshake: dial tcp: lookup mongo: no such host }, ] }
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe25a43]

goroutine 1 [running]:
iatp/cmd.glob..func4(0x1a7f740, {0x1039ae7, 0x5, 0x5})
	/go/src/iatp_opensource/cmd/web.go:55 +0x1a3
github.com/spf13/cobra.(*Command).execute(0x1a7f740, {0xc00011a910, 0x5, 0x5})
	/go/src/iatp_opensource/vendor/github.com/spf13/cobra/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0x1a7efc0)
	/go/src/iatp_opensource/vendor/github.com/spf13/cobra/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/iatp_opensource/vendor/github.com/spf13/cobra/command.go:902
iatp/cmd.Execute()
	/go/src/iatp_opensource/cmd/root.go:47 +0x25
main.main()
	/go/src/iatp_opensource/main.go:21 +0x17
[root@sculptor-virtual-machine home]#

**Comment by u-raison** [comment]
> 请问解决了嘛

没有。一直是这个提示：域注册失败: 未查询到域控制器.

**Comment by ayuxy** [comment]
> > 域控为windows server2022，搭建好后，web页面登陆数据库中没有用户，进入docker容器后重新初始化，显示无法查询到域控，具体如下：![图像](https://private-user-images.githubusercontent.com/67718036/305646904-ef25c96c-5d89-49b2-82fe-9cf1431396aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0OTc3NDAsIm5iZiI6MTcwODQ5NzQ0MCwicGF0aCI6Ii82NzcxODAzNi8zMDU2NDY5MDQtZWYyNWM5NmMtNWQ4OS00OWIyLTgyZmUtOWNmMTQzMTM5NmFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDA2MzcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiNTA2MjUyOGUzNzE4YjFkYzY2YmM4YmM4OTFkODIxZWJkNDY3NmQ3NGU2NGRjMTFjZmU0MTVjYmIyY2Y4MWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YFcD114ZAASNcQB-PndqXVlOmrK2sOtc3dsMl8CVoG8)
> > 是因为linux没有加入到域的原因吗？？？还是和windows server2022有关呀
> > 具体.env如下： #KAFKA配置，需修改为当前服务器的IP KAFKAHOST=192.168.131.128 KAFKAADV=PLAINTEXT://192.168.131.128:9092 BROKER=192.168.131.128:9092
> > #Mongo配置，默认账号密码 MONGOUSER=IATP MONGOPWD=IATP-by-360
> > #域控配置，其中DCUSER为域内用户的DN DCNAME="zgtest.local" DCSERVER=192.168.131.131 DCUSER="CN=Administrator,CN=Users,DC=zgtest,DC=local" DCPWD="Admin123"
> > #WEB配置，可配置为域内任意用户，或DCUSER的CN WEBUSER="Administrator"
> 
> @ayuxy 你的截图中使用的--username是Administrator，需要替换成DN：--username "CN=Administrator,CN=Users,DC=zgtest,DC=local"，再尝试下能否连上。

嗯嗯，晚上下班尝试下再反馈

**Comment by ayuxy** [comment]
> > 域控为windows server2022，搭建好后，web页面登陆数据库中没有用户，进入docker容器后重新初始化，显示无法查询到域控，具体如下： ![image](https://private-user-images.githubusercontent.com/67718036/305646904-ef25c96c-5d89-49b2-82fe-9cf1431396aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0OTc3NDAsIm5iZiI6MTcwODQ5NzQ0MCwicGF0aCI6Ii82NzcxODAzNi8zMDU2NDY5MDQtZWYyNWM5NmMtNWQ4OS00OWIyLTgyZmUtOWNmMTQzMTM5NmFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDA2MzcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiNTA2MjUyOGUzNzE4YjFkYzY2YmM4YmM4OTFkODIxZWJkNDY3NmQ3NGU2NGRjMTFjZmU0MTVjYmIyY2Y4MWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YFcD114ZAASNcQB-PndqXVlOmrK2sOtc3dsMl8CVoG8)
> > 是因为linux没有加入到域的原因吗 ？？？还是和windows server2022有关呀
> > 具体.env如下： #KAFKA配置，需修改为当前服务器的IP KAFKAHOST=192.168.131.128 KAFKAADV=PLAINTEXT://192.168.131.128:9092 BROKER=192.168.131.128:9092
> > #Mongo配置，默认账号密码 MONGOUSER=IATP MONGOPWD=IATP-by-360
> > #域控配置，其中DCUSER为域内用户的DN DCNAME="zgtest.local" DCSERVER=192.168.131.131 DCUSER="CN=Administrator,CN=Users,DC=zgtest,DC=local" DCPWD="Admin123"
> > #WEB配置，可配置为域内任意用户，或DCUSER的CN WEBUSER="Administrator"
> 
> @ayuxy 你的截图中使用的--username是Administrator，需要替换成DN：--username "CN=Administrator,CN=Users,DC=zgtest,DC=local"，再尝试下能否连上。

另外，大佬，想在企业内部搭建，如果搭建好后，adwatch因为一些原因崩了，对实际的域环境有影响嘛

**Comment by ayuxy** [comment]
> > > 域控为windows server2022，搭建好后，web页面登陆数据库中没有用户，进入docker容器后重新初始化，显示无法查询到域控，具体如下： ![image](https://private-user-images.githubusercontent.com/67718036/305646904-ef25c96c-5d89-49b2-82fe-9cf1431396aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0OTc3NDAsIm5iZiI6MTcwODQ5NzQ0MCwicGF0aCI6Ii82NzcxODAzNi8zMDU2NDY5MDQtZWYyNWM5NmMtNWQ4OS00OWIyLTgyZmUtOWNmMTQzMTM5NmFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDA2MzcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiNTA2MjUyOGUzNzE4YjFkYzY2YmM4YmM4OTFkODIxZWJkNDY3NmQ3NGU2NGRjMTFjZmU0MTVjYmIyY2Y4MWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YFcD114ZAASNcQB-PndqXVlOmrK2sOtc3dsMl8CVoG8)
> > > 是因为linux没有加入到域的原因吗 ？？？还是和windows server2022有关呀
> > > 具体.env如下： #KAFKA配置，需修改为当前服务器的IP KAFKAHOST=192.168.131.128 KAFKAADV=PLAINTEXT://192.168.131.128:9092 BROKER=192.168.131.128:9092
> > > #Mongo配置，默认账号密码 MONGOUSER=IATP MONGOPWD=IATP-by-360
> > > #域控配置，其中DCUSER为域内用户的DN DCNAME="zgtest.local" DCSERVER=192.168.131.131 DCUSER="CN=Administrator,CN=Users,DC=zgtest,DC=local" DCPWD="Admin123"
> > > #WEB配置，可配置为域内任意用户，或DCUSER的CN WEBUSER="Administrator"
> > 
> > 
> > @ayuxy 你的截图中使用的--username是Administrator，需要替换成DN：--username "CN=Administrator,CN=Users,DC=zgtest,DC=local"，再尝试下能否连上。
> 
> 另外，大佬，想在企业内部搭建，如果搭建好后，watchad因为一些原因崩了，对实际的域环境有影响嘛，另外大佬能建个相关的讨论群组不，方便大家有相关问题的讨论下呀

**Comment by rvnox** [comment]
> > > > 域控为windows server2022，搭建好后，web页面登陆数据库中没有用户，进入docker容器后重新初始化，显示无法查询到域控，具体如下：是
> > > > 因为linux没有加入到域控的原因吗？ windows server2022有呀
> > > > 具体.env如下： #KAFKA配置，需修改为当前服务器的IP KAFKAHOST=192.168.131.128 KAFKAADV=PLAINTEXT://192.168.131.128:9092 BROKER=192.168.131.128:9092 #Mongo
> > > > 配置，默认账号密码MONGOUSER=IATP MONGOPWD=IATP-by-360 
> > > > #域控配置，其中DCUSER为域内用户的DN DCNAME="zgtest.local" DCSERVER=192.168.131.131 DCUSER="CN=Administrator,CN=Users,DC=zgtest,DC =local" DCPWD="Admin123" 
> > > > #WEB配置，可配置为域内任意用户，或DCUSER的CN WEBUSER="Administrator"![图像](https://private-user-images.githubusercontent.com/67718036/305646904-ef25c96c-5d89-49b2-82fe-9cf1431396aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0OTc3NDAsIm5iZiI6MTcwODQ5NzQ0MCwicGF0aCI6Ii82NzcxODAzNi8zMDU2NDY5MDQtZWYyNWM5NmMtNWQ4OS00OWIyLTgyZmUtOWNmMTQzMTM5NmFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDA2MzcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiNTA2MjUyOGUzNzE4YjFkYzY2YmM4YmM4OTFkODIxZWJkNDY3NmQ3NGU2NGRjMTFjZmU0MTVjYmIyY2Y4MWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YFcD114ZAASNcQB-PndqXVlOmrK2sOtc3dsMl8CVoG8)
> > > 
> > > 
> > > @ayuxy你的截图中使用的--username是Administrator，需要替换成DN：--username "CN=Administrator,CN=Users,DC=zgtest,DC=local"，再尝试下能否连上。
> > 
> > 
> > 晚上再尝试下，想在企业内部搭建，如果搭建好后，因为一些原因崩溃了，对实际的域环境有影响嘛。另外大佬能建个相关的讨论群不，方便大家有相关问题的讨论下呀

**Comment by u-raison** [comment]
> > > > > 域控为windows server2022，搭建好后，web页面登陆数据库中没有用户，进入docker容器后重新初始化，显示无法查询到域控，具体如下：是
> > > > > 因为linux没有加入到域控的原因吗？ windows server2022有呀
> > > > > 具体.env如下： #KAFKA配置，需修改为当前服务器的IP KAFKAHOST=192.168.131.128 KAFKAADV=PLAINTEXT://192.168.131.128:9092 BROKER=192.168.131.128:9092 #Mongo
> > > > > 配置，默认账号密码MONGOUSER=IATP MONGOPWD=IATP-by-360
> > > > > #域控配置，其中DCUSER为域内用户的DN DCNAME="zgtest.local" DCSERVER=192.168.131.131 DCUSER="CN=Administrator,CN=Users,DC=zgtest,DC =local" DCPWD="Admin123"
> > > > > #WEB配置，可配置为域内任意用户，或DCUSER的CN WEBUSER="Administrator"![图像](https://private-user-images.githubusercontent.com/67718036/305646904-ef25c96c-5d89-49b2-82fe-9cf1431396aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0OTc3NDAsIm5iZiI6MTcwODQ5NzQ0MCwicGF0aCI6Ii82NzcxODAzNi8zMDU2NDY5MDQtZWYyNWM5NmMtNWQ4OS00OWIyLTgyZmUtOWNmMTQzMTM5NmFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDA2MzcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiNTA2MjUyOGUzNzE4YjFkYzY2YmM4YmM4OTFkODIxZWJkNDY3NmQ3NGU2NGRjMTFjZmU0MTVjYmIyY2Y4MWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YFcD114ZAASNcQB-PndqXVlOmrK2sOtc3dsMl8CVoG8)
> > > > 
> > > > 
> > > > @ayuxy你的截图中使用的--username是Administrator，需要替换成DN：--username "CN=Administrator,CN=Users,DC=zgtest,DC=local"，再尝试下能否连上。
> > > 
> > > 
> > > 晚上再尝试下，想在企业内部搭建，如果搭建好后，因为一些原因崩溃了，对实际的域环境有影响嘛。另外大佬能建个相关的讨论群不，方便大家有相关问题的讨论下呀

同求讨论群
