### ISSUE TITLE
请问下，web页面的默认账户密码是什么？

### ISSUE THREAD

**Issue by ethanye168** [Qihoo360/WatchAD2.0#2]
用docker搭建好了，但没法登录，不知道web页面的账户密码，麻烦告知下，谢谢

**Comment by meshfire0** [comment]
容器部署请参考[README.md]步骤五，在项目根目录下新建.env文件，在“域控配置”中通过DCUSER和DCPWD指定。

**Comment by ZJKai** [comment]
> 

为啥我通过DCUSER和DCPWD指定的用户登录，还是提示用户不存在登录不了？

**Comment by Cgaii** [comment]
> > 
> 
> 为啥我通过DCUSER和DCPWD指定的用户登录，还是提示用户不存在登录不了？

所有的登录走的都是ldap认证，可以确认下DCUSER和DCPWD在域内是否真实存在，密码正确才可以登录

**Comment by microqs** [comment]
遇到了相同的问题，使用的是域管账户，明明密码正确，登录提示“不存在该用户”。换了一个刚刚新建域账户的也不行，登录时还是提示“不存在该用户”

**Comment by ZJKai** [comment]
DCUSER加上@域名就不会提示“不存在该用户”，但是登录后还是报错。

**Comment by Cgaii** [comment]
@ZJKai @microqs 
DCUSER配置的是域管用户名(eg:iatp)，还是配置了带有OU的DN(eg:CN=iatp, OU=System, DC=demo, DC=com)

**Comment by Cgaii** [comment]
> DCUSER加上@域名就不会提示“不存在该用户”，但是登录后还是报错。

具体报错是什么呢？

**Comment by ZJKai** [comment]
> > DCUSER加上@域名就不会提示“不存在该用户”，但是登录后还是报错。
> 
> 具体报错是什么呢？

Web登录页面提示“Network error”。

这是容器watchad20-iatp-1的报错
[HTTP Server] http: panic serving : runtime error: index out of range [0] with length 0
goroutine 40 [running]:
net/http.(*conn).serve.func1(0xc00067e500)
        /usr/local/go/src/net/http/server.go:1801 +0x147
panic(0x1251060, 0xc0002c4c00)
        /usr/local/go/src/runtime/panic.go:975 +0x47a
iatp/iatp_wbm/controllers.(*UserController).PostLogin(0xc000032720, 0x0, 0x0)
        /go/src/iatp_opensource/iatp_wbm/controllers/user_controller.go:140 +0x856
reflect.Value.call(0x1229fa0, 0xc000032720, 0x1613, 0x12f07c5, 0x4, 0x1d68040, 0x0, 0x0, 0x7, 0xc0000eb800, ...)
        /usr/local/go/src/reflect/value.go:476 +0x8c7
reflect.Value.Call(0x1229fa0, 0xc000032720, 0x1613, 0x1d68040, 0x0, 0x0, 0x1613, 0xc0002d6080, 0x0)
        /usr/local/go/src/reflect/value.go:337 +0xb9
github.com/kataras/iris/v12/mvc.(*ControllerActivator).handlerOf.func2(0x159eb20, 0xc000294d80)
        /go/src/iatp_opensource/vendor/github.com/kataras/iris/v12/mvc/controller.go:497 +0x3cb
github.com/kataras/iris/v12/context.DefaultNext(0x159eb20, 0xc000294d80)
        /go/src/iatp_opensource/vendor/github.com/kataras/iris/v12/context/context.go:1343 +0x10c
github.com/kataras/iris/v12/context.(*context).Next(0xc000294d80)
        /go/src/iatp_opensource/vendor/github.com/kataras/iris/v12/context/context.go:1352 +0x3e
github.com/kataras/iris/v12/sessions.(*Sessions).Handler.func1(0x159eb20, 0xc000294d80)
        /go/src/iatp_opensource/vendor/github.com/kataras/iris/v12/sessions/sessions.go:105 +0x12d
github.com/kataras/iris/v12/context.Do(0x159eb20, 0xc000294d80, 0xc0000137a0, 0x2, 0x2)
        /go/src/iatp_opensource/vendor/github.com/kataras/iris/v12/context/context.go:1030 +0x82
github.com/kataras/iris/v12/context.(*context).Do(0xc000294d80, 0xc0000137a0, 0x2, 0x2)
        /go/src/iatp_opensource/vendor/github.com/kataras/iris/v12/context/context.go:1217 +0x55
github.com/kataras/iris/v12/core/router.(*routerHandler).HandleRequest(0xc0003becc0, 0x159eb20, 0xc000294d80)
        /go/src/iatp_opensource/vendor/github.com/kataras/iris/v12/core/router/handler.go:250 +0x562
github.com/kataras/iris/v12/core/router.(*Router).BuildRouter.func1(0x15766a0, 0xc0002e27e0, 0xc000508000)
        /go/src/iatp_opensource/vendor/github.com/kataras/iris/v12/core/router/router.go:135 +0x8f
github.com/kataras/iris/v12/core/router.(*Router).ServeHTTP(0xc00007f860, 0x15766a0, 0xc0002e27e0, 0xc000508000)
        /go/src/iatp_opensource/vendor/github.com/kataras/iris/v12/core/router/router.go:227 +0x48
net/http.serverHandler.ServeHTTP(0xc0001aa0e0, 0x15766a0, 0xc0002e27e0, 0xc000508000)
        /usr/local/go/src/net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc00067e500, 0x157a3a0, 0xc00061b900)
        /usr/local/go/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2969 +0x36c

**Comment by Cgaii** [comment]
> 

启动iatp，有报错日志吗？

**Comment by Cgaii** [comment]
> > > DCUSER加上@域名就不会提示“不存在该用户”，但是登录后还是报错。
> > 
> > 
> > 具体报错是什么呢？
> 
> Web登录页面提示“Network error”。
> 
> 这是容器watchad20-iatp-1的报错 [HTTP Server] http: panic serving : runtime error: index out of range [0] with length 0 goroutine 40 [running]: net/http.(*conn).serve.func1(0xc00067e500) /usr/local/go/src/net/http/server.go:1801 +0x147 panic(0x1251060, 0xc0002c4c00) /usr/local/go/src/runtime/panic.go:975 +0x47a iatp/iatp_wbm/controllers.(*UserController).PostLogin(0xc000032720, 0x0, 0x0) /go/src/iatp_opensource/iatp_wbm/controllers/user_controller.go:140 +0x856 reflect.Value.call(0x1229fa0, 0xc000032720, 0x1613, 0x12f07c5, 0x4, 0x1d68040, 0x0, 0x0, 0x7, 0xc0000eb800, ...) /usr/local/go/src/reflect/value.go:476 +0x8c7 reflect.Value.Call(0x1229fa0, 0xc000032720, 0x1613, 0x1d68040, 0x0, 0x0, 0x1613, 0xc0002d6080, 0x0) /usr/local/go/src/reflect/value.go:337 +0xb9 github.com/kataras/iris/v12/mvc.(*ControllerActivator).handlerOf.func2(0x159eb20, 0xc000294d80) /go/src/iatp_opensource/vendor/github.com/kataras/iris/v12/mvc/controller.go:497 +0x3cb github.com/kataras/iris/v12/context.DefaultNext(0x159eb20, 0xc000294d80) /go/src/iatp_opensource/vendor/github.com/kataras/iris/v12/context/context.go:1343 +0x10c github.com/kataras/iris/v12/context.(*context).Next(0xc000294d80) /go/src/iatp_opensource/vendor/github.com/kataras/iris/v12/context/context.go:1352 +0x3e github.com/kataras/iris/v12/sessions.(*Sessions).Handler.func1(0x159eb20, 0xc000294d80) /go/src/iatp_opensource/vendor/github.com/kataras/iris/v12/sessions/sessions.go:105 +0x12d github.com/kataras/iris/v12/context.Do(0x159eb20, 0xc000294d80, 0xc0000137a0, 0x2, 0x2) /go/src/iatp_opensource/vendor/github.com/kataras/iris/v12/context/context.go:1030 +0x82 github.com/kataras/iris/v12/context.(*context).Do(0xc000294d80, 0xc0000137a0, 0x2, 0x2) /go/src/iatp_opensource/vendor/github.com/kataras/iris/v12/context/context.go:1217 +0x55 github.com/kataras/iris/v12/core/router.(*routerHandler).HandleRequest(0xc0003becc0, 0x159eb20, 0xc000294d80) /go/src/iatp_opensource/vendor/github.com/kataras/iris/v12/core/router/handler.go:250 +0x562 github.com/kataras/iris/v12/core/router.(*Router).BuildRouter.func1(0x15766a0, 0xc0002e27e0, 0xc000508000) /go/src/iatp_opensource/vendor/github.com/kataras/iris/v12/core/router/router.go:135 +0x8f github.com/kataras/iris/v12/core/router.(*Router).ServeHTTP(0xc00007f860, 0x15766a0, 0xc0002e27e0, 0xc000508000) /go/src/iatp_opensource/vendor/github.com/kataras/iris/v12/core/router/router.go:227 +0x48 net/http.serverHandler.ServeHTTP(0xc0001aa0e0, 0x15766a0, 0xc0002e27e0, 0xc000508000) /usr/local/go/src/net/http/server.go:2843 +0xa3 net/http.(*conn).serve(0xc00067e500, 0x157a3a0, 0xc00061b900) /usr/local/go/src/net/http/server.go:1925 +0x8ad created by net/http.(*Server).Serve /usr/local/go/src/net/http/server.go:2969 +0x36c


启动iatp，有报错日志吗？

**Comment by Sculptor-liu** [comment]
[root@localhost WatchAD2.0-master]# docker logs 6f7cdf890877
[+] DZZJY 域注册失败: 未查询到域控制器.
创建日志缓存....
[-]认证域配置失败:数据库中未注册该域信息, mongo: no documents in result
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe25a43]

goroutine 1 [running]:
iatp/cmd.glob..func4(0x1a7f740, {0x1039ae7, 0x5, 0x5})
	/go/src/iatp_opensource/cmd/web.go:55 +0x1a3
github.com/spf13/cobra.(*Command).execute(0x1a7f740, {0xc00008ab90, 0x5, 0x5})
	/go/src/iatp_opensource/vendor/github.com/spf13/cobra/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0x1a7efc0)
	/go/src/iatp_opensource/vendor/github.com/spf13/cobra/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/iatp_opensource/vendor/github.com/spf13/cobra/command.go:902
iatp/cmd.Execute()
	/go/src/iatp_opensource/cmd/root.go:47 +0x25
main.main()
	/go/src/iatp_opensource/main.go:21 +0x17
==> engine.log <==

==> web.log <==

==> engine.log <==
{"appName":"IATP Engine","file":"iatp.go","func":"iatp/iatp.registerBypassplugins","level":"info","msg":"加载实时日志检测插件","plugin_name":"Certificate Active","time":"2024-02-19 07:07:04"}
{"appName":"IATP Engine","file":"iatp.go","func":"iatp/iatp.registerBypassplugins","level":"info","msg":"加载实时日志检测插件","plugin_name":"TGT Activities","time":"2024-02-19 07:07:04"}
{"appName":"IATP Engine","file":"iatp.go","func":"iatp/iatp.registerBypassplugins","level":"info","msg":"加载实时日志检测插件","plugin_name":"AS-REP Abnormal Response","time":"2024-02-19 07:07:04"}
{"appName":"IATP Engine","file":"iatp.go","func":"iatp/iatp.registerBypassplugins","level":"info","msg":"加载实时日志检测插件","plugin_name":"NTLM Relay","time":"2024-02-19 07:07:04"}
{"appName":"IATP Engine","file":"iatp.go","func":"iatp/iatp.registerBypassplugins","level":"info","msg":"加载实时日志检测插件","plugin_name":"Reset Account Password","time":"2024-02-19 07:07:04"}
{"appName":"IATP Engine","file":"iatp.go","func":"iatp/iatp.registerBypassplugins","level":"info","msg":"加载实时日志检测插件","plugin_name":"Kerberoasting","time":"2024-02-19 07:07:04"}
{"appName":"IATP Engine","file":"iatp.go","func":"iatp/iatp.registerBypassplugins","level":"info","msg":"加载实时日志检测插件","plugin_name":"Clear Log","time":"2024-02-19 07:07:04"}
{"appName":"IATP Engine","file":"iatp.go","func":"iatp/iatp.registerBypassplugins","level":"info","msg":"加载实时日志检测插件","plugin_name":"Close Log Service","time":"2024-02-19 07:07:04"}
{"appName":"IATP Engine","file":"iatp.go","func":"iatp/iatp.registerBypassplugins","level":"info","msg":"加载实时日志检测插件","plugin_name":"JuicyPotato","time":"2024-02-19 07:07:04"}
{"appName":"IATP Engine","file":"iatp.go","func":"iatp/iatp.registerBypassplugins","level":"info","msg":"加载实时日志检测插件","plugin_name":"SpoolSample","time":"2024-02-19 07:07:04"}
{"appName":"IATP Engine","file":"iatp.go","func":"iatp/iatp.registerBypassplugins","level":"info","msg":"加载实时日志检测插件","plugin_name":"Remote Code Execute","time":"2024-02-19 07:07:04"}
{"appName":"IATP Engine","file":"iatp.go","func":"iatp/iatp.registerBypassplugins","level":"info","msg":"加载实时日志检测插件","plugin_name":"SID History","time":"2024-02-19 07:07:04"}
{"appName":"IATP Engine","file":"iatp.go","func":"iatp/iatp.registerBypassplugins","level":"info","msg":"加载实时日志检测插件","plugin_name":"Similar Dc User","time":"2024-02-19 07:07:04"}
{"appName":"IATP Engine","file":"iatp.go","func":"iatp/iatp.registerBypassplugins","level":"info","msg":"加载实时日志检测插件","plugin_name":"ADCS-ESC","time":"2024-02-19 07:07:04"}
{"appName":"IATP Engine","file":"iatp.go","func":"iatp/iatp.registerBypassplugins","level":"info","msg":"加载实时日志检测插件","plugin_name":"SPN Jacking","time":"2024-02-19 07:07:04"}
{"appName":"IATP Engine","file":"iatp.go","func":"iatp/iatp.registerBypassplugins","level":"info","msg":"加载实时日志检测插件","plugin_name":"ZeroLogon","time":"2024-02-19 07:07:04"}
{"appName":"IATP Engine","file":"iatp.go","func":"iatp/iatp.registerBypassplugins","level":"info","msg":"加载实时日志检测插件","plugin_name":"DCShadow","time":"2024-02-19 07:07:04"}
{"appName":"IATP Engine","file":"iatp.go","func":"iatp/iatp.registerBypassplugins","level":"info","msg":"加载实时日志检测插件","plugin_name":"samAccountName Spoofing","time":"2024-02-19 07:07:04"}
{"appName":"IATP Engine","file":"iatp.go","func":"iatp/iatp.registerBypassplugins","level":"info","msg":"加载实时日志检测插件","plugin_name":"Abnormal Permissions","time":"2024-02-19 07:07:04"}
{"appName":"IATP Engine","file":"iatp.go","func":"iatp/iatp.registerBypassplugins","level":"info","msg":"加载实时日志检测插件","plugin_name":"Create Machine User","time":"2024-02-19 07:07:04"}
{"appName":"IATP Engine","file":"iatp.go","func":"iatp/iatp.registerBypassplugins","level":"info","msg":"加载实时日志检测插件","plugin_name":"NEW GPO","time":"2024-02-19 07:07:04"}
{"appName":"IATP Engine","file":"iatp.go","func":"iatp/iatp.registerBypassplugins","level":"info","msg":"加载实时日志检测插件","plugin_name":"DCSync","time":"2024-02-19 07:07:04"}
{"appName":"IATP Engine","file":"iatp.go","func":"iatp/iatp.registerBypassplugins","level":"info","msg":"加载实时日志检测插件","plugin_name":"Explicit Credential","time":"2024-02-19 07:07:04"}
{"appName":"IATP Engine","file":"iatp.go","func":"iatp/iatp.registerBypassplugins","level":"info","msg":"加载实时日志检测插件","plugin_name":"Skeleton Key","time":"2024-02-19 07:07:04"}
{"appName":"IATP Engine","file":"iatp.go","func":"iatp/iatp.registerBypassplugins","level":"info","msg":"加载实时日志检测插件","plugin_name":"Local Dump Ntds","time":"2024-02-19 07:07:04"}
{"appName":"IATP Engine","file":"iatp.go","func":"iatp/iatp.registerBypassplugins","level":"info","msg":"加载实时日志检测插件","plugin_name":"Resource Based Constraint Delegation","time":"2024-02-19 07:07:04"}
{"appName":"IATP Engine","file":"iatp.go","func":"iatp/iatp.registerBypassplugins","level":"info","msg":"加载实时日志检测插件","plugin_name":"GPO DELEGATION","time":"2024-02-19 07:07:04"}
{"appName":"IATP Engine","file":"iatp.go","func":"iatp/iatp.registerBypassplugins","level":"info","msg":"加载实时日志检测插件","plugin_name":"Shadow Credentials","time":"2024-02-19 07:07:04"}
{"appName":"IATP Engine","file":"iatp.go","func":"iatp/iatp.registerBypassplugins","level":"info","msg":"加载实时日志检测插件","plugin_name":"MS17-010","time":"2024-02-19 07:07:04"}
{"appName":"IATP Engine","file":"iatp.go","func":"iatp/iatp.registerBypassplugins","level":"info","msg":"加载实时日志检测插件","plugin_name":"DSRM Change","time":"2024-02-19 07:07:04"}
{"appName":"IATP Engine","file":"iatp.go","func":"iatp/iatp.Start","level":"info","msg":"IATP 配置加载完成","time":"2024-02-19 07:07:04"}
{"appName":"IATP Engine","file":"iatp.go","func":"iatp/iatp.Start.func3","level":"info","msg":"计划任务服务启动完成","time":"2024-02-19 07:07:04"}
{"appName":"IATP Engine","file":"iatp.go","func":"iatp/iatp.registerSourceEvent","level":"info","msg":"数据来源启动","source_name":"ITEvent","time":"2024-02-19 07:07:04"}
2024/02/19 07:04:29 Sarama consumer up and running!...

==> web.log <==
Now listening on: http://0.0.0.0
Application started. Press CTRL+C to shut down.
[root@localhost WatchAD2.0-master]#
